#!/bin/bash
#REPLACE="\$fakeroot \$cmd"

FILE="/theos/bin"
FILE1="/var$FILE"

if [ -d "$FILE" ]; then
	FAKEROOT=$FILE
#	FIX="\$fakeroot perl $FILE/\$cmd"
elif [ -d "$FILE1" ]; then
	FAKEROOT=$FILE1
#	FIX="\$fakeroot perl $FILE1/\$cmd"
else
	echo "Theos isnt installed... and thats probably you're issue. Please install Theos."
	exit 1;
fi

cp -f "/Library/Application Support/Theos Auto Installer/fakeroot.sh" $FAKEROOT

#n=1

#IFS=$'\n'

#while read LINE; do
# reading each line
#	if [ "$LINE" != "$REPLACE" ]; then
#		if [ "$LINE" == "#!/bin/bash" ]; then
#			TEXT="${LINE}"
#		else
#			TEXT="${TEXT}
#${LINE}"
#		fi
#	else
#		TEXT="${TEXT}
#${LINE}
#${FIX}"
#	fi

#	n=$((n+1))
#done < $FAKEROOT

#echo "$TEXT" > $FAKEROOT

echo "Theos should now work as expected!"
exit 0;